CREATE TABLE organizacoes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(150) NOT NULL,
    ativo       BOOLEAN DEFAULT TRUE,
    version     BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),

    CONSTRAINT pk_organizacoes PRIMARY KEY (id)
);

CREATE INDEX idx_organizacoes_nome ON organizacoes(nome);

CREATE TABLE entidades (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao      BIGINT NOT NULL,
    nome                VARCHAR(150) NOT NULL,
    nome_fantasia       VARCHAR(150),
    inscricao_estadual  VARCHAR(20),
    telefone            VARCHAR(20),
    ativo               BOOLEAN DEFAULT TRUE,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),

    CONSTRAINT pk_entidades PRIMARY KEY (id),
    CONSTRAINT fk_entidades_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id)
);

CREATE INDEX idx_entidades_id_organizacao ON entidades(id_organizacao);
CREATE INDEX idx_entidades_nome ON entidades(nome);

CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_entidade BIGINT NOT NULL,
    username    VARCHAR(50) NOT NULL,
    nome        VARCHAR(100) NOT NULL,
    senha       VARCHAR(255) NOT NULL,
    perfil      VARCHAR(1) NOT NULL,
    ativo       BOOLEAN DEFAULT TRUE,
    version     BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),

    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT fk_usuarios_entidade FOREIGN KEY (id_entidade)
        REFERENCES entidades(id),
    CONSTRAINT uk_usuarios_username UNIQUE (username),
    CONSTRAINT ck_usuarios_perfil CHECK (perfil IN ('A', 'D', 'G', 'O'))
);

CREATE INDEX idx_usuarios_id_entidade ON usuarios(id_entidade);
CREATE INDEX idx_usuarios_nome ON usuarios(nome);
