CREATE TABLE fichas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao      BIGINT NOT NULL,
    nome                VARCHAR(150) NOT NULL,
    frase               VARCHAR(255),
    idade               INTEGER,
    naturalidade        VARCHAR(120),
    classe_personagem   VARCHAR(80),
    altura_cm           NUMERIC(6, 2),
    peso_kg             NUMERIC(6, 2),
    tipo_fisico         VARCHAR(80),
    indole              VARCHAR(80),
    ranking             INTEGER,
    ocupacao            VARCHAR(120),
    reputacao           INTEGER,
    dinheiro            NUMERIC(15, 2),
    pontos_vida         INTEGER,
    equipe              VARCHAR(120),
    pontos              INTEGER,
    photoplayer         VARCHAR(120),
    player              VARCHAR(120),
    biografia           TEXT,
    anotacoes           TEXT,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),

    CONSTRAINT pk_fichas PRIMARY KEY (id),
    CONSTRAINT fk_fichas_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT uk_fichas_organizacao_nome UNIQUE (id_organizacao, nome),
    CONSTRAINT ck_fichas_idade CHECK (idade IS NULL OR idade >= 0),
    CONSTRAINT ck_fichas_ranking CHECK (ranking IS NULL OR ranking >= 0),
    CONSTRAINT ck_fichas_reputacao CHECK (reputacao IS NULL OR reputacao >= 0),
    CONSTRAINT ck_fichas_pontos_vida CHECK (pontos_vida IS NULL OR pontos_vida >= 0),
    CONSTRAINT ck_fichas_pontos CHECK (pontos IS NULL OR pontos >= 0)
);

CREATE INDEX idx_fichas_id_organizacao ON fichas(id_organizacao);
CREATE INDEX idx_fichas_nome ON fichas(nome);

CREATE TABLE ficha_relacionados (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    id_ficha        BIGINT NOT NULL,
    nome            VARCHAR(150) NOT NULL,
    relacao         VARCHAR(120),
    ordem           INTEGER NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_ficha_relacionados PRIMARY KEY (id),
    CONSTRAINT fk_ficha_relacionados_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT fk_ficha_relacionados_ficha FOREIGN KEY (id_ficha)
        REFERENCES fichas(id) ON DELETE CASCADE
);

CREATE INDEX idx_ficha_relacionados_id_ficha ON ficha_relacionados(id_ficha);

CREATE TABLE ficha_habilidades (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    id_ficha        BIGINT NOT NULL,
    nome            VARCHAR(120) NOT NULL,
    descricao       TEXT,
    ordem           INTEGER NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_ficha_habilidades PRIMARY KEY (id),
    CONSTRAINT fk_ficha_habilidades_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT fk_ficha_habilidades_ficha FOREIGN KEY (id_ficha)
        REFERENCES fichas(id) ON DELETE CASCADE
);

CREATE INDEX idx_ficha_habilidades_id_ficha ON ficha_habilidades(id_ficha);

CREATE TABLE ficha_conquistas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    id_ficha        BIGINT NOT NULL,
    tipo            VARCHAR(40) NOT NULL,
    nome            VARCHAR(150) NOT NULL,
    data_conquista  DATE,
    ordem           INTEGER NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_ficha_conquistas PRIMARY KEY (id),
    CONSTRAINT fk_ficha_conquistas_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT fk_ficha_conquistas_ficha FOREIGN KEY (id_ficha)
        REFERENCES fichas(id) ON DELETE CASCADE
);

CREATE INDEX idx_ficha_conquistas_id_ficha ON ficha_conquistas(id_ficha);
CREATE INDEX idx_ficha_conquistas_tipo ON ficha_conquistas(tipo);

CREATE TABLE ficha_pokemons (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao      BIGINT NOT NULL,
    id_ficha            BIGINT NOT NULL,
    box                 VARCHAR(80),
    pokebola            VARCHAR(80),
    apelido             VARCHAR(120) NOT NULL,
    especie             VARCHAR(120) NOT NULL,
    genero              VARCHAR(20),
    sobre               TEXT,
    ability             VARCHAR(120),
    feature             VARCHAR(120),
    nature              VARCHAR(120),
    hold_item           VARCHAR(120),
    happiness_atual     INTEGER,
    happiness_max       INTEGER,
    combo               VARCHAR(255),
    hp                  INTEGER,
    atk                 INTEGER,
    def                 INTEGER,
    satk                INTEGER,
    sdef                INTEGER,
    speed               INTEGER,
    pwr                 INTEGER,
    stm                 INTEGER,
    skl                 INTEGER,
    jmp                 INTEGER,
    contest_speed       INTEGER,
    ordem               INTEGER NOT NULL DEFAULT 0,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),

    CONSTRAINT pk_ficha_pokemons PRIMARY KEY (id),
    CONSTRAINT fk_ficha_pokemons_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT fk_ficha_pokemons_ficha FOREIGN KEY (id_ficha)
        REFERENCES fichas(id) ON DELETE CASCADE,
    CONSTRAINT ck_ficha_pokemons_happiness_atual CHECK (happiness_atual IS NULL OR happiness_atual >= 0),
    CONSTRAINT ck_ficha_pokemons_happiness_max CHECK (happiness_max IS NULL OR happiness_max >= 0)
);

CREATE INDEX idx_ficha_pokemons_id_ficha ON ficha_pokemons(id_ficha);
CREATE INDEX idx_ficha_pokemons_especie ON ficha_pokemons(especie);

CREATE TABLE ficha_pokemon_movimentos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    id_ficha        BIGINT NOT NULL,
    id_pokemon      BIGINT NOT NULL,
    nome            VARCHAR(120) NOT NULL,
    categoria       VARCHAR(40),
    ordem           INTEGER NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_ficha_pokemon_movimentos PRIMARY KEY (id),
    CONSTRAINT fk_ficha_pokemon_movimentos_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT fk_ficha_pokemon_movimentos_ficha FOREIGN KEY (id_ficha)
        REFERENCES fichas(id) ON DELETE CASCADE,
    CONSTRAINT fk_ficha_pokemon_movimentos_pokemon FOREIGN KEY (id_pokemon)
        REFERENCES ficha_pokemons(id) ON DELETE CASCADE
);

CREATE INDEX idx_ficha_pokemon_movimentos_id_pokemon ON ficha_pokemon_movimentos(id_pokemon);

CREATE TABLE ficha_itens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    id_ficha        BIGINT NOT NULL,
    categoria       VARCHAR(60) NOT NULL,
    codigo          VARCHAR(40),
    nome            VARCHAR(150) NOT NULL,
    quantidade      INTEGER NOT NULL DEFAULT 0,
    descricao       TEXT,
    ordem           INTEGER NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_ficha_itens PRIMARY KEY (id),
    CONSTRAINT fk_ficha_itens_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT fk_ficha_itens_ficha FOREIGN KEY (id_ficha)
        REFERENCES fichas(id) ON DELETE CASCADE,
    CONSTRAINT ck_ficha_itens_quantidade CHECK (quantidade >= 0)
);

CREATE INDEX idx_ficha_itens_id_ficha ON ficha_itens(id_ficha);
CREATE INDEX idx_ficha_itens_categoria ON ficha_itens(categoria);

CREATE TABLE ficha_registros (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    id_ficha        BIGINT NOT NULL,
    tipo_movimento  VARCHAR(20) NOT NULL,
    descricao       TEXT NOT NULL,
    data_registro   DATE,
    ordem           INTEGER NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_ficha_registros PRIMARY KEY (id),
    CONSTRAINT fk_ficha_registros_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT fk_ficha_registros_ficha FOREIGN KEY (id_ficha)
        REFERENCES fichas(id) ON DELETE CASCADE
);

CREATE INDEX idx_ficha_registros_id_ficha ON ficha_registros(id_ficha);
CREATE INDEX idx_ficha_registros_data ON ficha_registros(data_registro);
