CREATE TABLE ficha_historicos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    id_ficha        BIGINT NOT NULL,
    lote            VARCHAR(36) NOT NULL,
    acao            VARCHAR(20) NOT NULL,
    campo           VARCHAR(255) NOT NULL,
    valor_anterior  TEXT,
    valor_novo      TEXT,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_ficha_historicos PRIMARY KEY (id),
    CONSTRAINT fk_ficha_historicos_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT fk_ficha_historicos_ficha FOREIGN KEY (id_ficha)
        REFERENCES fichas(id) ON DELETE CASCADE,
    CONSTRAINT ck_ficha_historicos_acao CHECK (acao IN ('ADICIONADO', 'REMOVIDO', 'ALTERADO'))
);

CREATE INDEX idx_ficha_historicos_id_ficha ON ficha_historicos(id_ficha);
CREATE INDEX idx_ficha_historicos_created_at ON ficha_historicos(created_at);

-- Contas públicas eram criadas como ADMIN. Apenas vinni permanece administrador.
UPDATE usuarios
SET perfil = 'O'
WHERE perfil = 'A'
  AND LOWER(username) <> 'vinni';

UPDATE usuarios
SET perfil = 'A'
WHERE LOWER(username) = 'vinni';
