CREATE TABLE ficha_timeline_entradas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    id_ficha        BIGINT NOT NULL,
    secao           VARCHAR(80) NOT NULL,
    periodo         VARCHAR(120),
    titulo          VARCHAR(180) NOT NULL,
    subtitulo       VARCHAR(255),
    conteudo        TEXT NOT NULL,
    cor             VARCHAR(24),
    ordem           INTEGER NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_ficha_timeline_entradas PRIMARY KEY (id),
    CONSTRAINT fk_ficha_timeline_entradas_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT fk_ficha_timeline_entradas_ficha FOREIGN KEY (id_ficha)
        REFERENCES fichas(id) ON DELETE CASCADE
);

CREATE INDEX idx_ficha_timeline_entradas_ficha
    ON ficha_timeline_entradas(id_ficha, ordem);

WITH alvo AS (
    SELECT id, id_organizacao
    FROM fichas
    WHERE LOWER(COALESCE(player, '')) IN ('luks', 'luksnmds', 'lucas')
)
INSERT INTO ficha_timeline_entradas (
    id_organizacao, id_ficha, secao, periodo, titulo, subtitulo, conteudo, cor, ordem
)
SELECT
    alvo.id_organizacao,
    alvo.id,
    dados.secao,
    dados.periodo,
    dados.titulo,
    dados.subtitulo,
    dados.conteudo,
    dados.cor,
    dados.ordem
FROM alvo
CROSS JOIN (
    VALUES
        (
            'Caderno de ideias',
            'Nota editorial',
            'Mudança de paradigma',
            'Rascunhos e ideias para a reescrita de Nendo',
            '<p>A história anterior mantinha pontas soltas entre a base do mundo Pokémon, a base do RPG e a base da religião. A proposta é que o fantástico continue existindo, mas seja interpretado de formas diferentes conforme cultura, época e acesso ao conhecimento.</p><p><strong>Divisão das ideias:</strong> cosmologia como verdade absoluta, mitologia como verdade interpretada e história como verdade provada.</p><blockquote>Os Duxies funcionam como o sistema imunológico do planeta: não protegem os lendários, mas o equilíbrio, contra aquilo que o ameaça - humano ou Pokémon.</blockquote><p>Os deuses nascem e morrem pela crença humana. Eles existem e influenciam nas sombras, mas não são uma verdade absoluta conhecida pela humanidade.</p>',
            '#aeb5bf',
            10
        ),
        (
            'Acontecimentos históricos',
            'I - Criação',
            'A Criação',
            'O Vazio, Arceus e a primeira lei',
            '<p>No princípio existia apenas o Vazio. Dele surgiu Arceus, o Primeiro, cuja vontade deu origem ao Tempo, ao Espaço e à Matéria através de Dialga, Palkia e Giratina.</p><ol><li><strong>O Surgimento de Arceus.</strong> Do Vazio nasce o Primeiro, responsável pela Criação.</li><li><strong>O Nascimento do Universo.</strong> Tempo, Espaço e Matéria estabelecem as bases do mundo.</li><li><strong>A Origem da Vida.</strong> Divindades representam emoções, vida, morte e natureza; incontáveis espécies passam a ocupar seus lugares.</li><li><strong>O Nascimento dos Guardiões.</strong> Arceus cria seres encarregados de proteger a harmonia da Criação.</li><li><strong>A Criação da Humanidade.</strong> Os Guardiões concedem livre-arbítrio e capacidade de transformação aos humanos.</li><li><strong>A Primeira Lei.</strong> Onde humanos e Pokémon coexistem, um Guardião caminha oculto sob forma humana para preservar o equilíbrio. Ao longo das eras, eles passam a ser conhecidos como Duxies.</li></ol>',
            '#8f9baf',
            20
        ),
        (
            'Acontecimentos históricos',
            'II - Nendo',
            'A formação do arquipélago',
            'Tempo, Espaço e o Mar Desconhecido',
            '<p>Muitos ciclos após a formação do mundo, Dialga e Palkia caminharam sobre a Terra em busca de um lugar onde Tempo e Espaço coexistissem em perfeita harmonia. Ali ergueram um santuário.</p><p>Das profundezas do oceano elevaram um vasto arquipélago. A proximidade entre essas forças primordiais rompeu as águas e deu origem às distorções que seriam conhecidas como o Mar Desconhecido.</p><p>Com as eras, espécies de Pokémon chegaram ao arquipélago e foram moldadas pelas forças de Nendo. Mais tarde, os primeiros humanos chegaram às costas orientais, ergueram assentamentos e fizeram cumprir a Primeira Lei: um Guardião passou a caminhar entre ambas as espécies.</p>',
            '#79a6b8',
            30
        ),
        (
            'Acontecimentos históricos',
            'III - Platūna',
            'A Era da Monarquia',
            'O Reino de Platuna e as lendas do Guardião',
            '<p>Com o passar das gerações, os primeiros assentamentos deram lugar a pequenas comunidades fortificadas. Humanos e Pokémon ainda eram estranhos entre si; as criaturas selvagens eram temidas, e os homens eram vistos como invasores.</p><p>Cercados por florestas, montanhas e espécies poderosas, os humanos ergueram muralhas. Aldeias passaram a reconhecer uma única linhagem, formando o Reino de Platuna e inaugurando a Era da Monarquia.</p><p>Enquanto os reinos cresciam, o Duxie permanecia oculto. Relatos sobre um viajante respeitado por criaturas ferozes foram transformados em lendas, até que a figura do Guardião desapareceu da memória da humanidade.</p>',
            '#b49b73',
            40
        ),
        (
            'Acontecimentos jogados',
            'Em organização',
            'Marcos a integrar',
            'Eventos jogados, causados por players ou narração',
            '<p>Lista de marcos reunidos no documento para desenvolvimento cronológico:</p><ul><li>Guerra das Fadas; Ho-Oh divide a região; fundação do Reino de Platuna no East Side.</li><li>Revolucionários se opõem à monarquia do Rei Helder; descoberta do tipo Light; o reino é envolvido pelo metal de Melmetal.</li><li>Morte do Rei Helder, dissolução de KP, criação da Cintilação e migração dos sobreviventes para o Leste; parte deles funda Orre.</li><li>Fundação do Progenitus Camp; Pol torna-se campeão de Nendo; Hiroshi Dukun, Ryuu e Wock atuam como scouts.</li><li>Bruno e Pol fazem um pacto com Afrodite; Nicho nasce, desaparece e depois entra em coma após ser envenenado por Primarina.</li><li>Aiden busca a cura, encontra Bruno, descobre o parentesco de Nicho e segue a jornada das três joias.</li><li>A Chaos Jewel provoca a primeira erupção do vulcão de Kraka; Calestia e Baltei evitam a catástrofe com Aiden.</li><li>Surgem Murkrow infectados, ocorre o primeiro Pokérus, e Bill assume os NightBleed após o fim da Team Margeon.</li><li>Bruno torna-se prefeito de Neo T; Deuses Modernos ascendem; Cresselia é morta durante um torneio e os pesadelos se espalham por Nendo.</li></ul>',
            '#9b789d',
            50
        )
) AS dados(secao, periodo, titulo, subtitulo, conteudo, cor, ordem)
WHERE NOT EXISTS (
    SELECT 1
    FROM ficha_timeline_entradas existente
    WHERE existente.id_ficha = alvo.id
);
