ALTER TABLE fichas ADD COLUMN id_usuario BIGINT;

ALTER TABLE fichas
    ADD CONSTRAINT fk_fichas_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id);

CREATE INDEX idx_fichas_id_usuario ON fichas(id_usuario);

UPDATE fichas ficha
SET id_usuario = usuario.id
FROM usuarios usuario
WHERE ficha.id_usuario IS NULL
  AND ficha.created_by IS NOT NULL
  AND LOWER(TRIM(ficha.created_by)) = LOWER(TRIM(usuario.username));

UPDATE fichas ficha
SET id_usuario = usuario.id
FROM usuarios usuario
WHERE ficha.id_usuario IS NULL
  AND ficha.npc = FALSE
  AND ficha.player IS NOT NULL
  AND LOWER(TRIM(ficha.player)) = LOWER(TRIM(usuario.nome));

CREATE TABLE loja_itens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    categoria       VARCHAR(60) NOT NULL,
    codigo          VARCHAR(80),
    icone           TEXT,
    nome            VARCHAR(150) NOT NULL,
    descricao       TEXT,
    preco           NUMERIC(15, 2) NOT NULL,
    ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    ordem           INTEGER NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_loja_itens PRIMARY KEY (id),
    CONSTRAINT fk_loja_itens_organizacao FOREIGN KEY (id_organizacao)
        REFERENCES organizacoes(id),
    CONSTRAINT ck_loja_itens_preco CHECK (preco >= 0)
);

CREATE INDEX idx_loja_itens_organizacao_ativo ON loja_itens(id_organizacao, ativo);
