CREATE TABLE integracao_autorizacoes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario      BIGINT NOT NULL,
    id_entidade     BIGINT NOT NULL,
    id_organizacao  BIGINT NOT NULL,
    codigo_hash     VARCHAR(64) NOT NULL,
    expira_em       TIMESTAMP NOT NULL,
    usado_em        TIMESTAMP,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT pk_integracao_autorizacoes PRIMARY KEY (id),
    CONSTRAINT uk_integracao_autorizacoes_codigo UNIQUE (codigo_hash),
    CONSTRAINT fk_integracao_autorizacoes_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_integracao_autorizacoes_entidade FOREIGN KEY (id_entidade) REFERENCES entidades(id) ON DELETE CASCADE,
    CONSTRAINT fk_integracao_autorizacoes_organizacao FOREIGN KEY (id_organizacao) REFERENCES organizacoes(id) ON DELETE CASCADE
);

CREATE INDEX idx_integracao_autorizacoes_expira_em ON integracao_autorizacoes(expira_em);
